/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public.route'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicProjectsRouteImport } from './routes/_public.projects'
import { Route as PublicResumeRouteImport } from './routes/_public.resume'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicProjectsRoute = PublicProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicResumeRoute = PublicResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => PublicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/projects': typeof PublicProjectsRoute
  '/resume': typeof PublicResumeRoute
}
export interface FileRoutesByTo {
  '/projects': typeof PublicProjectsRoute
  '/resume': typeof PublicResumeRoute
  '/': typeof PublicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/_public/projects': typeof PublicProjectsRoute
  '/_public/resume': typeof PublicResumeRoute
  '/_public/': typeof PublicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects' | '/resume'
  fileRoutesByTo: FileRoutesByTo
  to: '/projects' | '/resume' | '/'
  id:
    | '__root__'
    | '/_public'
    | '/_public/projects'
    | '/_public/resume'
    | '/_public/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/projects': {
      id: '/_public/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof PublicProjectsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/resume': {
      id: '/_public/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof PublicResumeRouteImport
      parentRoute: typeof PublicRouteRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicProjectsRoute: typeof PublicProjectsRoute
  PublicResumeRoute: typeof PublicResumeRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicProjectsRoute: PublicProjectsRoute,
  PublicResumeRoute: PublicResumeRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
